# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "devel_release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'devel_release'

      # Download and install ChimeraX
      - name: Install ChimeraX
        run: |
          wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1b7iKWNEZHVC2O7O1OYgKdJ7KmIkq_KIl' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1b7iKWNEZHVC2O7O1OYgKdJ7KmIkq_KIl" -O chimerax.deb && rm -rf /tmp/cookies.txt
          sudo apt-get install ./chimerax.deb
          chimerax --version
        
      # Runs a set of commands using the runners shell
      - name: Build ArtiaX
        run: |
          chimerax --nogui --cmd "devel clean ${GITHUB_WORKSPACE} ; exit;"
          chimerax --nogui --cmd "devel build ${GITHUB_WORKSPACE} ; exit;"
      
      # Update the latest release
      - name: Update development release
        uses: eine/tip@master
        with:
          tag: latest_build
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*.whl
